# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Tom Cook
tagline:             HORSE
url:                 https://tom.horse
paginate:            1
baseurl:             "https://tom.horse"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Tom Cook
  url:               https://twitter.com/ywxwy

pages_list:
  About:    '/about'
  Archive:  '/archive'
